export { ReactComponent as PlusIcon } from './plus.svg'
export { ReactComponent as XIcon } from './x.svg'
export { ReactComponent as ErrorIcon } from './error.svg'
export { ReactComponent as NoticeIcon } from './notice.svg'
export { ReactComponent as WarningIcon } from './warning.svg'
export { ReactComponent as NotebookIcon } from './notebook.svg'
export { ReactComponent as WriteIcon } from './write.svg'
export { ReactComponent as ArrowIcon } from './arrow.svg'
